/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package conversor;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
/**
 *
 * @author jesic
 */
public class ConversorGenerico extends javax.swing.JFrame {
   // private static final double CONSTANTE_PULG_CENT = 2.54;
    private boolean convertirValor1;
    List<Conversor> conversores;
    private Conversor conversorSeleccionado;
    /**
     * Creates new form Conversor
     */
    public ConversorGenerico() {
        initComponents();
        setTitle("Conversor");
        //centra la ventana en la pantalla
        setLocationRelativeTo(null);
        
        //lleno la lista con los tipos de conversores que tengo
        conversores=new ArrayList<Conversor>();
        conversores.add(new CentimetrosPulgadasConversor());
        conversores.add(new MetrosKilometrosConversor());
        conversores.add(new LitrosGalonesConversor());
        conversores.add(new GramosOnzasConversor());
        conversores.add(new PesosDolarConversor());
        conversores.add(new PesosEuroConversor());
        
        //Lenar el combo con el tipo de conversiones que puedo hacer, dependiendo de los conversores que tenga e la lista
        //por lo que itero la lista y muestro el valor de cada item 
        for (Conversor conversor : conversores) {
            jComboBoxConversores.addItem(conversor.toString());
        }
        
        conversorSeleccionado=conversores.get(0);
        //seteo que por defecto me aparezca en el label1 el valor del primer item que tengo en la lista de conversores
        jLabel1.setText(conversorSeleccionado.getLabelValor1());
        jLabel2.setText(conversorSeleccionado.getLableValor2());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldValor1 = new javax.swing.JTextField();
        jButtonConvertir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldValor2 = new javax.swing.JTextField();
        jComboBoxConversores = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Valor 1");

        jTextFieldValor1.setToolTipText("");
        jTextFieldValor1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldValor1FocusLost(evt);
            }
        });
        jTextFieldValor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldValor1KeyPressed(evt);
            }
        });

        jButtonConvertir.setText("Convertir");
        jButtonConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertirActionPerformed(evt);
            }
        });

        jLabel2.setText("Valor 2");

        jTextFieldValor2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldValor2FocusLost(evt);
            }
        });
        jTextFieldValor2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldValor2KeyPressed(evt);
            }
        });

        jComboBoxConversores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxConversoresItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxConversores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                        .addComponent(jButtonConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jComboBoxConversores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(jTextFieldValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jButtonConvertir))
                .addGap(18, 18, 18)
                .addComponent(jTextFieldValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertirActionPerformed
        if (convertirValor1) {
            convertirAValor2();
            
        } else {
            convertirAValor1();

        }
        
    }//GEN-LAST:event_jButtonConvertirActionPerformed

    private void convertirAValor1() throws HeadlessException {
        String pulgText = jTextFieldValor2.getText().replace(",", ".");
        Double pulg;
        try {
            pulg = Double.valueOf(pulgText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Hubo un error. Por favor verifique el numero ingresado", "ERROR", JOptionPane.ERROR_MESSAGE);
            return ;
        }
        Double cent = conversorSeleccionado.convertirValor2Valor1(pulg);
        jTextFieldValor1.setText(String.format("%.2f", cent));
        
    }

    private void convertirAValor2() throws HeadlessException {
        String centText = jTextFieldValor1.getText().replace(",", ".");
        Double cent;
        try {
            cent = Double.valueOf(centText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Hubo un error. Por favor verifique el numero ingresado.", "ERROR", JOptionPane.ERROR_MESSAGE);
            return ;
        }
        Double pulg = conversorSeleccionado.convertirValor1Valor2(cent);
        //System.out.println(pulg);
        jTextFieldValor2.setText(String.format("%.2f", pulg));
        
    }
    
     public void clearTxtField() {
        jTextFieldValor1.setText(null);
        jTextFieldValor2.setText(null);
    }
  
    private void jTextFieldValor1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldValor1FocusLost
        convertirValor1=true;
    }//GEN-LAST:event_jTextFieldValor1FocusLost

    private void jTextFieldValor2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldValor2FocusLost
        convertirValor1=false;
    }//GEN-LAST:event_jTextFieldValor2FocusLost

    private void jTextFieldValor1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldValor1KeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            convertirAValor2();
        }
    }//GEN-LAST:event_jTextFieldValor1KeyPressed

    private void jTextFieldValor2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldValor2KeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            convertirAValor1();
        }
    }//GEN-LAST:event_jTextFieldValor2KeyPressed

    private void jComboBoxConversoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxConversoresItemStateChanged
        int selectedIndex= jComboBoxConversores.getSelectedIndex();
        jLabel1.setText(conversores.get(selectedIndex).getLabelValor1());
        jLabel2.setText(conversores.get(selectedIndex).getLableValor2());
        conversorSeleccionado=conversores.get(selectedIndex);
        clearTxtField();
    }//GEN-LAST:event_jComboBoxConversoresItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversorGenerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversorGenerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversorGenerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversorGenerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversorGenerico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConvertir;
    private javax.swing.JComboBox<String> jComboBoxConversores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldValor1;
    private javax.swing.JTextField jTextFieldValor2;
    // End of variables declaration//GEN-END:variables
}
